server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/aopauth?allowMultiQueries=true
    username: root
    password: hackcity
    driver-class-name: org.gjt.mm.mysql.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    dbcp2:                     #进行数据库连接池的配置
      min-idle: 5             #数据库连接池的最小维持连接数
      max-idle: 5             #最大的连接数
      initial-size: 5        #初始化提供的连接数
      max-wait-millis: 200  #连接等待获取的最大超时时间
      validationQuery: SELECT 1
      testWhileIdle: false
      testOnBorrow: false
      testOnReturn: false

    #在这里配置Redis数据源
  redis:
    database: 0
    host: dataserver
    password: 123456
    port: 6379
    pool:
      max-active: 10
      max-idle: 8
      min-idle: 2
      max-wait: 100
    timeout: 10000
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
